### ISSUE TITLE
docker_postgres.sh doesn't use POSTGRES_DB env variable

### ISSUE THREAD

**Issue by PanierAvide** [developmentseed/osm-seed#262]
Hello,

The docker_postgres.sh script in db image doesn't make use of `POSTGRES_DB` environment variable, for example here (but also on following psql calls) : https://github.com/developmentseed/osm-seed/blob/0776d0594130b1c858e44313fdaaa5a6427e2c06/images/db/docker_postgres.sh#L9

If you change the DB name, the script throws an error due to missing "openstreetmap" database :

```
compose-db-1   | 2022-09-05 10:38:24.093 UTC [93] ERROR:  database "openstreetmap" does not exist
compose-db-1   | 2022-09-05 10:38:24.093 UTC [93] STATEMENT:  GRANT ALL PRIVILEGES ON DATABASE openstreetmap TO openstreetmap;
compose-db-1   | ERROR:  database "openstreetmap" does not exist
```

Best regards.

**Comment by batpad** [comment]
Thank you for the issue @PanierAvide . That makes sense - so far I don't think we've changed the db name since we keep it consistent for a deploy -- but this does seem like generally a good thing to make sure is configurable, especially since the docs and env file would indicate so :) - thank you for the catch!

@Rub21 would you be able to look?

**Comment by Rub21** [comment]
hey @PanierAvide , Thank you for reporting this issue. As you said the `POSTGRES_DB` has not been used, and the error come up when we change the DB name, in our use cases we have been leaving the DB as openstreetmap, maybe that us the reason why we did to get this error. I fixed the issue here: https://github.com/developmentseed/osm-seed/pull/263/files


cc. @batpad

**Comment by PanierAvide** [comment]
Thanks to both of you for fast answers and fixes :grinning:

**Comment by Rub21** [comment]
This is done, Closing the ticket!!
