### ISSUE TITLE
Dockerfile to create vector tiles from data

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-seed#5]
Needs to dump / export the data from the db, cut vector tiles, and push them to s3.

**Comment by Rub21** [comment]
After diving on some tiling technology and good ideas form:  @kamicut @geohacker and @batpad @danielfdsilva  , it comes up with good apps to build the tile server for osm-seed. 

Next actions: 

We are going to create containers that can quickly render the OSM data, for this target we need:

- Create a new PostGIS DB container to serve the data for rendering the map, to update the date on this container we may need to use: [osm2pgsql](https://github.com/openstreetmap/osm2pgsql) or [imposm3](https://imposm.org/static/rel/) 
 
- Create a [Tegola](https://github.com/go-spatial/tegola) container for rendering the tiles.

 *Note:*
We need to keep the PostGIS DB in a separate container and not in the same as the tiling server, because we may need to use in the future for other proposals.

cc. @olafveerman

**Comment by kamicut** [comment]
@Rub21 yes, you should generally keep 1 container for each process (i.e 1 container for the DB) or else you'll get into problems when processes exit.

**Comment by batpad** [comment]
We have Tegola now as part of osm-seed! Closing here.
